services:
  settings:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BACKEND_URL=http://172.17.0.2:3001
    ports:
      - "4000:3000"

networks:
  default:
