services:
  settings:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jadwal_masjid_web_app-settings
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - DB_HOST=jadwal_masjid_mysql
      - DB_USER=masjid
      - DB_PASSWORD=masjid123
      - DB_NAME=jadwal_masjid
    ports:
      - "4000:4000"
